version: '3.8'

services:
  user_service:
    build:
      context: ./backend
      dockerfile: Dockerfile.user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zennic
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - db
      - redis

  trading_service:
    build:
      context: ./backend
      dockerfile: Dockerfile.trading_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zennic
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zennic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
