name: zennic
options:
  bundleIdPrefix: com.zennic
  deploymentTarget:
    macOS: 14.0
  
targets:
  zennic:
    type: application
    platform: macOS
    sources: 
      - path: zennic
    info:
      path: zennic/Info.plist
      properties:
        CFBundleDisplayName: zennic
        LSApplicationCategoryType: public.app-category.finance
        LSMinimumSystemVersion: "14.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zennic.app
        SWIFT_VERSION: 5.0
        MACOSX_DEPLOYMENT_TARGET: 14.0
    entitlements:
      path: zennic/zennic.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
