name: zennic
options:
  bundleIdPrefix: com.example
targets:
  Core:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Core/Sources/Core
      - path: Features/Core/Sources/Cgit2
        excludes:
          - "**/*.h"
    dependencies:
      - target: Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Core"
        HEADER_SEARCH_PATHS:
          - $(SRCROOT)/Libraries/libgit2/install/include
          - $(SRCROOT)/Features/Core/Sources/Cgit2
          - $(SRCROOT)/Features/Core/Sources/Core/include
          - $(SRCROOT)/Features/Core/Sources/Cgit2/include
        MODULEMAP_FILE: $(SRCROOT)/Features/Core/Sources/Core/include/module.modulemap
        CLANG_ENABLE_MODULES: YES
        DEFINES_MODULE: YES
        SWIFT_INCLUDE_PATHS:
          - $(SRCROOT)/Features/Core/Sources/Core
          - $(SRCROOT)/Features/Core/Sources/Cgit2
          - $(SRCROOT)/Features/Core/Sources/Cgit2/include
          - $(SRCROOT)/Features/Shared/Sources/Shared
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/Libraries/libgit2/install/lib
        OTHER_LDFLAGS:
          - "-force_load"
          - "$(SRCROOT)/Libraries/libgit2/install/lib/libgit2.a"
          - "-lz"
          - "-liconv"
          - "-framework"
          - "GSS"
          - "-framework"
          - "CoreFoundation"
        PUBLIC_HEADERS_FOLDER_PATH: $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).framework/Headers
        SWIFT_INSTALL_OBJC_HEADER: NO
        SWIFT_MODULE_NAME: Core
        OBJC_BRIDGING_HEADER: "$(SRCROOT)/Features/Core/Sources/Core/Core-Bridging-Header.h"
        OTHER_CFLAGS:
          - "-fmodule-map-file=$(SRCROOT)/Features/Core/Sources/Cgit2/module.modulemap"

  Shared:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Shared/Sources/Shared
        excludes:
          - "Views/SplitView/SplitViewState.swift"
          - "Views/SplitView/SplitViewItemProtocol.swift"
          - "Views/SplitView/SplitViewControllerType.swift"
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Shared"
        DEFINES_MODULE: "YES"

  DocumentsInterface:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Documents/Sources/DocumentsInterface
    dependencies:
      - target: Core
      - target: Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "DocumentsInterface"
        DEFINES_MODULE: "YES"

  Documents:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Documents/Sources/Documents
    dependencies:
      - target: Core
      - target: Shared
      - target: Editor
      - target: UtilityArea
      - target: DocumentsInterface
      - target: CodeEditorInterface
      - target: CodeEditor
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Documents"
        DEFINES_MODULE: "YES"

  Editor:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Editor/Sources/Editor
    dependencies:
      - target: Core
      - target: Shared
      - target: DocumentsInterface
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Editor"
        DEFINES_MODULE: "YES"

  UtilityArea:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/UtilityArea/Sources/UtilityArea
    dependencies:
      - target: Core
      - target: Shared
      - target: TerminalEmulator
      - target: DocumentsInterface
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "UtilityArea"
        DEFINES_MODULE: "YES"

  TerminalEmulator:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/TerminalEmulator/Sources/TerminalEmulator
    dependencies:
      - target: Core
      - target: Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "TerminalEmulator"
        DEFINES_MODULE: "YES"

  App:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: App/Main
    dependencies:
      - target: Core
      - target: CodeEditor
      - target: DataIntegration
      - target: RealTimeMonitoring
      - target: Backtesting
      - target: Visualization
      - target: UI
      - target: Documents
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "App"
        DEFINES_MODULE: "YES"
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/App $(SRCROOT)/Features/RealTimeMonitoring/Sources/RealTimeMonitoring/include"

  zennic:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources: 
      - path: App/Main
    dependencies:
      - target: App
      - target: UI
      - target: CodeEditor
      - target: Documents
    scheme:
      environmentVariables:
        ALPACA_ACCESS_TOKEN: ${ALPACA_ACCESS_TOKEN}
    info:
      path: App/Info.plist
      properties:
        CFBundleName: zennic
        CFBundleDisplayName: zennic
        CFBundleIdentifier: com.example.zennic
        CFBundleVersion: 1.0.0
        CFBundleShortVersionString: 1.0.0
        NSPrincipalClass: NSApplication
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""

  DataIntegration:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/DataIntegration/Sources/DataIntegration
    dependencies:
      - target: Core
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "DataIntegration"
        DEFINES_MODULE: "YES"

  CodeEditorInterface:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/CodeEditor/Sources/CodeEditorInterface
    dependencies:
      - target: Core
      - target: Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "CodeEditorInterface"
        DEFINES_MODULE: "YES"

  CodeEditor:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/CodeEditor/Sources/CodeEditor
    dependencies:
      - target: Core
      - target: CodeEditorInterface
      - target: Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "CodeEditor"
        DEFINES_MODULE: "YES"

  RealTimeMonitoring:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/RealTimeMonitoring/Sources
    dependencies:
      - target: Core
      - target: Documents
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "RealTimeMonitoring"
        DEFINES_MODULE: "YES"
        SWIFT_INCLUDE_PATHS: $(SRCROOT)/Features/RealTimeMonitoring/Sources

  Backtesting:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Backtesting/Views
    dependencies:
      - target: Core
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Backtesting"
        DEFINES_MODULE: "YES"

  Visualization:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/Visualization/Views
    dependencies:
      - target: Core
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "Visualization"
        DEFINES_MODULE: "YES"

  UI:
    type: framework
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Features/UI/Sources/UI
    dependencies:
      - target: Core
      - target: CodeEditorInterface
      - target: Shared
      - target: Documents
      - target: Editor
      - target: UtilityArea
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_MODULE_NAME: "UI"
        DEFINES_MODULE: "YES"
