name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Install Apple Certificate
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # Import certificate from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        
        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        
        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
    - name: Install Provisioning Profile
      env:
        PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
      run: |
        # Create variables
        PROFILE_PATH=$RUNNER_TEMP/profile.mobileprovision
        
        # Import profile from secrets
        echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PROFILE_PATH
        
        # Copy profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        
    - name: Build Archive
      env:
        PROFILE: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        xcodebuild archive \
          -scheme AIHedgeFund \
          -archivePath $RUNNER_TEMP/AIHedgeFund.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -allowProvisioningUpdates \
          DEVELOPMENT_TEAM="$TEAM_ID" \
          PROVISIONING_PROFILE_SPECIFIER="$PROFILE"
          
    - name: Export IPA
      env:
        PROFILE: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
      run: |
        xcodebuild -exportArchive \
          -archivePath $RUNNER_TEMP/AIHedgeFund.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $RUNNER_TEMP/export
          
    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
        APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
      run: |
        xcrun altool --upload-app -f $RUNNER_TEMP/export/AIHedgeFund.ipa \
          -t ios \
          -u "$APP_STORE_CONNECT_USERNAME" \
          -p "$APP_STORE_CONNECT_PASSWORD" \
          --verbose
